Emma/account creation footer
hs-credit-dev/frontend pull request #9
Opened 2022-06-24 18:23 UTC by emmayuan25

2022-06-26 23:06 UTC, ldb297 requested changes
Please change all exact pixel measurements to incorporate either view height, view width. 

maybe for font its okay to leave in exact pixel dimensions, but would recommend moving toward "em" and "rem" in the future. 

like the use of @media for widths, but where did you find these measurements? what is it based on? is this for phone screens, portrait tablets, and landscape screens?

overall, good work just make change for exact pixel dimensions

2022-06-26 23:12 UTC, hs-credit-dev requested changes
<img width="762" alt="Screen Shot 2022-06-26 at 4 10 27 PM" src="https://user-images.githubusercontent.com/94883722/175837361-b439a04d-b26d-4ff1-b76e-66512600473b.png">

also where are you incorporating the footer? i had to add it into app.js myself to test. 

this footer should carry across all screens right? so i would add it into the main app.js where it will eventually live. 

and attached is screenshot of what it looks like on my machine, it doesn't stretch across entire bottom of screen.

2022-06-30 00:24 UTC, hs-credit-dev approved these changes
nice work

2022-06-30 00:30 UTC, ldb297 approved these changes
great work

2022-06-30 00:45 UTC, BrownMY commented
lets import the footer into the app

2022-06-30 01:11 UTC, crlimacastro approved these changes

2022-06-30 01:11 UTC, crlimacastro commented on src/styles/footer.account.creation.styles.css
> +    width: 100%;
Might want 100vw to ensure footer always stretches across screen

2022-06-30 01:58 UTC, BrownMY submitted a review, later dismissed

2022-07-01 20:09 UTC, merged